"""
Data models for AI-Based 5G Digital Twin Network Simulator.

This module defines all Pydantic models used throughout the simulation system,
including configuration, traffic demands, allocation decisions, and metrics.
"""

from enum import Enum
from typing import Dict, Optional
from pydantic import BaseModel, Field, field_validator, ConfigDict


class UserType(str, Enum):
    """Enumeration of four user traffic types in the 5G network."""
    VIDEO_STREAMING = "video_streaming"
    ONLINE_GAMING = "online_gaming"
    IOT_DEVICES = "iot_devices"
    VOIP_MESSAGING = "voip_messaging"


class SimulationConfig(BaseModel):
    """
    Configuration parameters for simulation execution.
    
    All parameters are validated to ensure they fall within realistic ranges
    for 5G network simulation.
    """
    total_bandwidth: float = Field(
        default=100.0,
        ge=10.0,
        le=1000.0,
        description="Total bandwidth in Mbps"
    )
    base_latency: float = Field(
        default=10.0,
        ge=1.0,
        le=100.0,
        description="Base latency in milliseconds"
    )
    congestion_factor: float = Field(
        default=1.5,
        ge=1.0,
        le=10.0,
        description="Congestion multiplier"
    )
    packet_loss_rate: float = Field(
        default=2.0,
        ge=0.0,
        le=100.0,
        description="Packet loss percentage"
    )
    random_seed: Optional[int] = Field(
        default=None,
        description="Optional random seed for reproducible simulations"
    )


class TrafficDemand(BaseModel):
    """
    Traffic demand generated by a user type for a single simulation tick.
    
    Represents the resource requirements and characteristics of traffic
    from one user type during a 100ms time interval.
    """
    user_type: UserType
    bandwidth_demand: float = Field(
        ge=0.0,
        description="Requested bandwidth in Mbps"
    )
    latency_sensitivity: float = Field(
        ge=0.0,
        le=1.0,
        description="0=tolerant, 1=critical"
    )
    packet_count: int = Field(
        ge=0,
        description="Number of packets in this tick"
    )
    timestamp: float = Field(
        description="Simulation tick timestamp"
    )


class AllocationDecision(BaseModel):
    """
    Resource allocation result from an allocator.
    
    Contains the bandwidth distribution decision made by either the
    baseline or AI allocator for a single simulation tick.
    """
    allocations: Dict[UserType, float] = Field(
        description="Bandwidth allocated per user type in Mbps"
    )
    total_allocated: float = Field(
        description="Total bandwidth allocated"
    )
    strategy_name: str = Field(
        description="Name of allocation strategy"
    )
    timestamp: float = Field(
        description="Simulation tick timestamp"
    )
    
    @field_validator('total_allocated')
    @classmethod
    def validate_total(cls, v: float, info) -> float:
        """Ensure total allocated matches sum of individual allocations."""
        if 'allocations' in info.data:
            allocations_sum = sum(info.data['allocations'].values())
            if abs(v - allocations_sum) >= 0.01:
                raise ValueError(
                    f"Total allocated ({v}) doesn't match sum of allocations ({allocations_sum})"
                )
        return v


class UserTypeMetrics(BaseModel):
    """
    QoS metrics for a single user type.
    
    Captures the experienced quality of service for one user type
    during a simulation tick.
    """
    latency: float = Field(
        description="Experienced latency in ms"
    )
    throughput: float = Field(
        description="Achieved throughput in Mbps"
    )
    packet_loss: float = Field(
        ge=0.0,
        le=100.0,
        description="Packet loss percentage"
    )
    allocation_efficiency: float = Field(
        default=100.0,
        ge=0.0,
        le=100.0,
        description="Allocation efficiency score (0-100). Measures how well allocated bandwidth matches demand with headroom for bursts."
    )


class AllocationResult(BaseModel):
    """
    Complete allocation result with QoS metrics.
    
    Combines the allocation decision with the resulting QoS metrics
    for all user types and an aggregate QoS score.
    """
    decision: AllocationDecision
    metrics: Dict[UserType, UserTypeMetrics]
    qos_score: float = Field(
        ge=0.0,
        le=100.0,
        description="Aggregate QoS score"
    )


class StrategyRecommendation(BaseModel):
    """
    Strategic recommendation from Groq Override Layer.
    
    Contains AI-generated suggestions for adjusting allocation priorities
    along with natural language reasoning.
    """
    priority_adjustments: Dict[UserType, float] = Field(
        description="Suggested priority weight adjustments"
    )
    reasoning: str = Field(
        description="Natural language explanation"
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence in recommendation"
    )
    timestamp: float


class NetworkState(BaseModel):
    """
    Complete snapshot of network state for a simulation tick.
    
    Represents the entire state of the simulated network at a single
    point in time, including configuration, demands, allocation results,
    and AI explanations.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True, from_attributes=True)
    
    tick: int = Field(
        description="Current simulation tick number"
    )
    timestamp: float = Field(
        description="Wall clock timestamp"
    )
    config: SimulationConfig | dict
    demands: Dict[UserType, TrafficDemand]
    baseline_result: AllocationResult
    ai_result: AllocationResult
    rl_result: Optional[AllocationResult] = Field(
        default=None,
        description="RL allocator result"
    )
    congestion_level: float = Field(
        ge=0.0,
        le=1.0,
        description="Current congestion as fraction of capacity"
    )
    explanation: Optional[str] = Field(
        default=None,
        description="Natural language explanation from Groq"
    )
    explanation_timestamp: Optional[float] = Field(
        default=None
    )


class AllocatorStatistics(BaseModel):
    """
    Statistics for a single allocator over a time window.
    
    Aggregated performance metrics used for dashboard display
    and comparative analysis.
    """
    avg_latency_per_type: Dict[UserType, float]
    avg_throughput_per_type: Dict[UserType, float]
    avg_packet_loss_per_type: Dict[UserType, float]
    avg_qos_score: float


class MetricsStatistics(BaseModel):
    """
    Aggregated statistics over time window for both allocators.
    
    Provides comparative statistics between baseline and AI allocators
    for dashboard visualization.
    """
    window_size: int
    baseline_stats: AllocatorStatistics
    ai_stats: AllocatorStatistics
    improvement_percentage: float


class RLLearningStats(BaseModel):
    """
    Learning statistics for RL Multi-Armed Bandit allocator.
    
    Tracks the learning progress and current state of the RL allocator.
    """
    total_ticks: int = Field(
        description="Number of ticks the RL allocator has learned from"
    )
    avg_reward: float = Field(
        description="Average reward per tick (RL QoS - Baseline QoS)"
    )
    current_weights: Dict[UserType, float] = Field(
        description="Current priority weights being used"
    )
    exploration_rate: float = Field(
        ge=0.0,
        le=1.0,
        description="Current epsilon (exploration rate)"
    )
    best_weights_found: Dict[UserType, float] = Field(
        description="Best weights found so far (highest Q-values)"
    )
